version: "3.3"

services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:  
      - "3308:3308"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: rest_api

  nginx:
    container_name: nginx
    build: images/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "88:88"
    depends_on:
      - db

  php:
    container_name: php
    build: images/php
    volumes:
      - ./lumen:/var/www/html
    working_dir: /var/www/html/app/public
    command: php-fpm
    links:
      - db:db
    ports:
      - "9000:9000"
    depends_on:
      - db